version: "3"

services:
    rabbitmq:
        image: rabbitmq:3.5.7
        restart: on-failure:5 
        ports:
          - 5672:5672
        environment:
            RABBITMQ_DEFAULT_USER: remote_guest
            RABBITMQ_DEFAULT_PASS: remote_guest

    flower:
        image: mher/flower
        environment: 
            - CELERY_BROKER_URL=amqp://remote_guest:remote_guest@rabbitmq:5672/
            - FLOWER_PORT=5555
        ports: 
            - 5555:5555
    celery:
        build: ./
        command: celery -A settings worker -l info
        volumes:
            - ./:/usr/src/code        

    web:
        build: ./
        restart: on-failure:5
        command: python3 manage.py runserver 0.0.0.0:8000
        ports: 
          - 80:8000
        volumes:
            - ./:/usr/src/code

