version: "3"

services:

    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    flower_redis:
        image: mher/flower
        environment: 
            CELERY_BROKER_URL: ${REDIS_CELERY_BROKER_URL}
            FLOWER_PORT: 5555
        ports: 
            - 5555:5555

    celery_redis:
        build: ./
        command: celery -A settings.celery_redis worker -l info
        environment:
            REDIS_CELERY_APP_NAME: ${REDIS_CELERY_APP_NAME}
            REDIS_CELERY_BROKER_URL: ${REDIS_CELERY_BROKER_URL}
            REDIS_CELERY_RESULT_BACKEND: ${REDIS_CELERY_RESULT_BACKEND}
            RABBITMQ_CELERY_APP_NAME: ${RABBITMQ_CELERY_APP_NAME}
            RABBITMQ_CELERY_BROKER_URL: ${RABBITMQ_CELERY_BROKER_URL}
            RABBITMQ_CELERY_RESULT_BACKEND: ${RABBITMQ_CELERY_RESULT_BACKEND}
        volumes:
            - ./:/usr/src/code

    rabbitmq:
        image: rabbitmq:3.5.7
        ports:
          - 5672:5672
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    flower_rabbitmq:
        image: mher/flower
        environment: 
            CELERY_BROKER_URL: ${RABBITMQ_CELERY_BROKER_URL}
            FLOWER_PORT: 5556
        ports: 
            - 5556:5556

    celery_rabbitmq:
        build: ./
        command: celery -A settings.celery_rabbitmq worker -l info
        environment:
            REDIS_CELERY_APP_NAME: ${REDIS_CELERY_APP_NAME}
            REDIS_CELERY_BROKER_URL: ${REDIS_CELERY_BROKER_URL}
            REDIS_CELERY_RESULT_BACKEND: ${REDIS_CELERY_RESULT_BACKEND}
            RABBITMQ_CELERY_APP_NAME: ${RABBITMQ_CELERY_APP_NAME}
            RABBITMQ_CELERY_BROKER_URL: ${RABBITMQ_CELERY_BROKER_URL}
            RABBITMQ_CELERY_RESULT_BACKEND: ${RABBITMQ_CELERY_RESULT_BACKEND}
        volumes:
            - ./:/usr/src/code

    web:
        build: ./
        command: python3 manage.py runserver 0.0.0.0:8000 --verbosity 2
        environment:
            REDIS_CELERY_APP_NAME: ${REDIS_CELERY_APP_NAME}
            REDIS_CELERY_BROKER_URL: ${REDIS_CELERY_BROKER_URL}
            REDIS_CELERY_RESULT_BACKEND: ${REDIS_CELERY_RESULT_BACKEND}
            RABBITMQ_CELERY_APP_NAME: ${RABBITMQ_CELERY_APP_NAME}
            RABBITMQ_CELERY_BROKER_URL: ${RABBITMQ_CELERY_BROKER_URL}
            RABBITMQ_CELERY_RESULT_BACKEND: ${RABBITMQ_CELERY_RESULT_BACKEND}
        ports: 
          - 80:8000
        volumes:
            - ./:/usr/src/code

